// <auto-generated />
using System;
using BookRecords.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookRecords.Migrations
{
    [DbContext(typeof(BookRecordsContext))]
    [Migration("20221016082054_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("Idauthor")
                        .HasColumnType("int")
                        .HasColumnName("Idauthor");

                    b.Property<int>("Idbook")
                        .HasColumnType("int")
                        .HasColumnName("Idbook");

                    b.HasKey("Idauthor", "Idbook")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "Idauthor" }, "fk_author_authorbooks_idx");

                    b.HasIndex(new[] { "Idbook" }, "fk_book_authorbooks_idx");

                    b.ToTable("AuthorBooks", (string)null);
                });

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.Property<int>("Idbook")
                        .HasColumnType("int")
                        .HasColumnName("Idbook");

                    b.Property<int>("Idcategory")
                        .HasColumnType("int")
                        .HasColumnName("Idcategory");

                    b.HasKey("Idbook", "Idcategory")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "Idbook" }, "fk_book_bookcategories_idx");

                    b.HasIndex(new[] { "Idcategory" }, "fk_category_bookcategories_idx");

                    b.ToTable("BookCategories", (string)null);
                });

            modelBuilder.Entity("BookRecords.Data.Entities.Author", b =>
                {
                    b.Property<int>("Idauthor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Idauthor");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Lastname");

                    b.HasKey("Idauthor")
                        .HasName("PRIMARY");

                    b.ToTable("Author", (string)null);
                });

            modelBuilder.Entity("BookRecords.Data.Entities.Book", b =>
                {
                    b.Property<int>("Idbook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Idbook");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BookName");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Isbn");

                    b.Property<DateTime?>("ReleaseYear")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReleaseYear");

                    b.Property<string>("Type")
                        .HasColumnType("enum('Hardcover','Paperback','Digital','Comicbook')")
                        .HasColumnName("Type");

                    b.HasKey("Idbook")
                        .HasName("PRIMARY");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("BookRecords.Data.Entities.Category", b =>
                {
                    b.Property<int>("Idcategory")
                        .HasColumnType("int")
                        .HasColumnName("Idcategory");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CategoryName");

                    b.HasKey("Idcategory")
                        .HasName("PRIMARY");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("BookRecords.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("IdRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Iduser")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TokenSalt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("IdRefreshToken")
                        .HasName("PRIMARY");

                    b.HasIndex("Iduser");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("BookRecords.Data.Entities.User", b =>
                {
                    b.Property<int>("Iduser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Iduser");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Firstname")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Firstname");

                    b.Property<string>("Lastname")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Password");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Username");

                    b.HasKey("Iduser")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Username" }, "Username_UNIQUE")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("UserBook", b =>
                {
                    b.Property<int>("Iduser")
                        .HasColumnType("int")
                        .HasColumnName("Iduser");

                    b.Property<int>("Idbook")
                        .HasColumnType("int")
                        .HasColumnName("Idbook");

                    b.HasKey("Iduser", "Idbook")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "Idbook" }, "fk_book_userbooks_idx");

                    b.HasIndex(new[] { "Iduser" }, "fk_user_userbooks_idx");

                    b.ToTable("UserBooks", (string)null);
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("BookRecords.Data.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("Idauthor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_author_authorbooks");

                    b.HasOne("BookRecords.Data.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("Idbook")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_book_authorbooks");
                });

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.HasOne("BookRecords.Data.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("Idbook")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_book_bookcategories");

                    b.HasOne("BookRecords.Data.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("Idcategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_bookcategories");
                });

            modelBuilder.Entity("BookRecords.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("BookRecords.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("Iduser")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserBook", b =>
                {
                    b.HasOne("BookRecords.Data.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("Idbook")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_book_userbooks");

                    b.HasOne("BookRecords.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Iduser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_userbooks");
                });

            modelBuilder.Entity("BookRecords.Data.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
